"""Suggestion catalog for the Duo integration.

Every entry is intentionally written at a suggestive, non-graphic level.
The application proposes a theme and a mood, never an explicit, step by
step description of a sexual act. It is up to the couple to decide, in
the moment and within the limits they set in their own profile, how far
they want to take any given suggestion.
"""

from .const import (
    CATEGORY_COMMUNICATION,
    CATEGORY_INTENSITE_PLUS,
    CATEGORY_JEU_DE_ROLE,
    CATEGORY_MASSAGE,
    CATEGORY_PRELIMINAIRES,
    CATEGORY_SENSORIEL,
)

# intensity: 1 (très doux) -> 5 (torride)
ACTIVITIES = [
    {
        "id": "preliminaires_baiser",
        "category": CATEGORY_PRELIMINAIRES,
        "name": "Baiser prolongé",
        "description": "Un baiser qui dure aussi longtemps que vous le souhaitez, sans se presser.",
        "intensity": 1,
        "duration_min": 2,
        "duration_max": 10,
        "accessory": None,
    },
    {
        "id": "preliminaires_compliment",
        "category": CATEGORY_PRELIMINAIRES,
        "name": "Compliment chuchoté",
        "description": "Chuchotez à l'oreille de votre partenaire ce que vous appréciez le plus chez lui/elle ce soir.",
        "intensity": 1,
        "duration_min": 2,
        "duration_max": 5,
        "accessory": None,
    },
    {
        "id": "preliminaires_caresses_guidees",
        "category": CATEGORY_PRELIMINAIRES,
        "name": "Caresses guidées",
        "description": "Guidez la main de votre partenaire là où vous aimeriez être touché(e) ce soir.",
        "intensity": 2,
        "duration_min": 3,
        "duration_max": 10,
        "accessory": None,
    },
    {
        "id": "preliminaires_striptease",
        "category": CATEGORY_PRELIMINAIRES,
        "name": "Effeuillage lent",
        "description": "Un déshabillage joueur et sans précipitation, chacun son tour.",
        "intensity": 2,
        "duration_min": 3,
        "duration_max": 8,
        "accessory": None,
    },
    {
        "id": "sensoriel_bandeau",
        "category": CATEGORY_SENSORIEL,
        "name": "Bandeau surprise",
        "description": "Les yeux bandés, laissez votre partenaire vous surprendre par le toucher.",
        "intensity": 3,
        "duration_min": 5,
        "duration_max": 15,
        "accessory": "bandeau",
    },
    {
        "id": "sensoriel_glacon",
        "category": CATEGORY_SENSORIEL,
        "name": "Glaçon et chaleur",
        "description": "Alternez des sensations froides et chaudes sur la peau, doucement.",
        "intensity": 3,
        "duration_min": 5,
        "duration_max": 10,
        "accessory": "glaçons",
    },
    {
        "id": "sensoriel_plume",
        "category": CATEGORY_SENSORIEL,
        "name": "Plume et duvet",
        "description": "Des caresses très légères, du bout d'une plume, sur les zones les plus sensibles.",
        "intensity": 2,
        "duration_min": 5,
        "duration_max": 10,
        "accessory": "plume",
    },
    {
        "id": "massage_huile",
        "category": CATEGORY_MASSAGE,
        "name": "Massage à l'huile",
        "description": "Un massage sensuel à l'huile, en silence ou en musique, à tour de rôle.",
        "intensity": 2,
        "duration_min": 10,
        "duration_max": 20,
        "accessory": "huile de massage",
    },
    {
        "id": "massage_dos",
        "category": CATEGORY_MASSAGE,
        "name": "Détente du dos",
        "description": "Concentrez le massage sur le dos et la nuque, pour faire redescendre la pression avant la suite.",
        "intensity": 1,
        "duration_min": 5,
        "duration_max": 15,
        "accessory": None,
    },
    {
        "id": "jeu_de_role_rencontre",
        "category": CATEGORY_JEU_DE_ROLE,
        "name": "Rencontre inconnue",
        "description": "Imaginez, le temps d'une soirée, que vous vous rencontrez pour la première fois.",
        "intensity": 3,
        "duration_min": 10,
        "duration_max": 20,
        "accessory": None,
    },
    {
        "id": "jeu_de_role_scenario",
        "category": CATEGORY_JEU_DE_ROLE,
        "name": "Scénario au choix",
        "description": "Chacun propose un petit scénario à jouer ensemble ce soir, sans détails imposés à l'avance.",
        "intensity": 3,
        "duration_min": 10,
        "duration_max": 20,
        "accessory": None,
    },
    {
        "id": "jeu_de_role_ordres_doux",
        "category": CATEGORY_JEU_DE_ROLE,
        "name": "Consigne du soir",
        "description": "L'un donne une consigne simple à suivre, l'autre est toujours libre de l'accepter ou non.",
        "intensity": 3,
        "duration_min": 5,
        "duration_max": 15,
        "accessory": None,
    },
    {
        "id": "communication_fantasme",
        "category": CATEGORY_COMMUNICATION,
        "name": "Confession d'un fantasme",
        "description": "Partagez un fantasme que vous n'avez encore jamais essayé ensemble.",
        "intensity": 1,
        "duration_min": 5,
        "duration_max": 15,
        "accessory": None,
    },
    {
        "id": "communication_question_torride",
        "category": CATEGORY_COMMUNICATION,
        "name": "Question intime",
        "description": "Piochez une question intime à laquelle répondre honnêtement, à tour de rôle.",
        "intensity": 1,
        "duration_min": 5,
        "duration_max": 10,
        "accessory": None,
    },
    {
        "id": "communication_liste_envies",
        "category": CATEGORY_COMMUNICATION,
        "name": "Liste à deux",
        "description": "Complétez ensemble une liste de choses que vous aimeriez essayer un jour.",
        "intensity": 1,
        "duration_min": 5,
        "duration_max": 15,
        "accessory": None,
    },
    {
        "id": "intensite_carte_blanche",
        "category": CATEGORY_INTENSITE_PLUS,
        "name": "Carte blanche",
        "description": "Le partenaire dont c'est le tour prend l'initiative et fait monter la température, dans le respect des limites fixées dans votre profil.",
        "intensity": 5,
        "duration_min": 10,
        "duration_max": 30,
        "accessory": None,
    },
    {
        "id": "intensite_nouveaute",
        "category": CATEGORY_INTENSITE_PLUS,
        "name": "Nouveauté assumée",
        "description": "Retentez, à deux, quelque chose que vous aviez décliné auparavant — uniquement si vous en avez tous les deux réellement envie ce soir.",
        "intensity": 4,
        "duration_min": 10,
        "duration_max": 25,
        "accessory": None,
    },
    {
        "id": "intensite_negociation",
        "category": CATEGORY_INTENSITE_PLUS,
        "name": "À négocier ensemble",
        "description": "Discutez ensemble de quelque chose de nouveau à essayer ce soir, et mettez-vous d'accord avant de vous lancer.",
        "intensity": 4,
        "duration_min": 10,
        "duration_max": 30,
        "accessory": None,
    },
    {
        "id": "intensite_rythme",
        "category": CATEGORY_INTENSITE_PLUS,
        "name": "Défi de rythme",
        "description": "Alternez qui mène le rythme du moment, en changeant à chaque sonnerie du minuteur.",
        "intensity": 5,
        "duration_min": 10,
        "duration_max": 20,
        "accessory": None,
    },
]


def get_activity(activity_id: str) -> dict | None:
    """Return the activity matching the given id, if any."""
    for activity in ACTIVITIES:
        if activity["id"] == activity_id:
            return activity
    return None
